import BST from "./bst";

const tree = new BST()
tree.insert(5)
tree.insert(8)
tree.insert(2)
tree.insert(3)
tree.insert(1)
tree.insert(7)
tree.insert(6)
tree.insert(9)
// console.log(tree.preOrderTraversal())
// console.log(tree.inOrderTraversal())
// console.log(tree.postOrderTraversal())
// console.log(tree.levelOrderTraversal())
// console.log(tree.getHeight())
// console.log(tree.has(1))
console.log(tree.remove(2))
console.log(tree.inOrderTraversal())